spring.application.name=yourscrm-mono-server

spring.docker.compose.file=dev/docker-compose.yaml
spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.profiles.active=local

spring.threads.virtual.enabled=true

logging.pattern.dateformat=yyMMddHHmmss.SSS
logging.pattern.level=%.-1p
