<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.yourscrm</groupId>
        <artifactId>yourscrm</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>frontend</artifactId>
    <packaging>pom</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-version}</version>
                <executions>
                    <execution>
                        <id>auth_api_gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/../api/oas/auth.yaml</inputSpec>
                            <output>./apis/auth</output>
                            <configOptions>
                                <npmName>@yourscrm/auth</npmName>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <generatorName>typescript-fetch</generatorName>
                    <cleanupOutput>true</cleanupOutput>
                    <configOptions>
                        <supportsES6>false</supportsES6>
                    </configOptions>
                    <typeMappings>
                        <typeMapping>integer+int64=string</typeMapping>
                    </typeMappings>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
