<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.yourscrm</groupId>
        <artifactId>backend</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>apis</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>backend-auth-api</module>
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-version}</version>
                <configuration>
                    <generatorName>spring</generatorName>
                    <generateSupportingFiles>false</generateSupportingFiles>
                    <configOptions>
                        <openApiNullable>false</openApiNullable>
                        <interfaceOnly>true</interfaceOnly>
                        <requestMappingMode>api_interface</requestMappingMode>
                        <skipDefaultInterface>true</skipDefaultInterface>
                        <useSpringBoot3>true</useSpringBoot3>
                        <useResponseEntity>true</useResponseEntity>
                        <documentationProvider>none</documentationProvider>
                        <generateBuilders>true</generateBuilders>
                    </configOptions>
                    <typeMappings>
                        <typeMapping>number+decimal=BigDecimal</typeMapping>
                    </typeMappings>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>